/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  WolfPosition,
} from './components/wolf/wolf.model';

export namespace Components {
  interface GApp {}
  interface GEgg {
    'nest': number;
    'wolfPosition': 'left-top' | 'left-bottom' | 'right-top' | 'right-bottom';
  }
  interface GWolf {
    'position': WolfPosition;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NavButton {
    'direction': 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom';
  }
}

declare global {


  interface HTMLGAppElement extends Components.GApp, HTMLStencilElement {}
  var HTMLGAppElement: {
    prototype: HTMLGAppElement;
    new (): HTMLGAppElement;
  };

  interface HTMLGEggElement extends Components.GEgg, HTMLStencilElement {}
  var HTMLGEggElement: {
    prototype: HTMLGEggElement;
    new (): HTMLGEggElement;
  };

  interface HTMLGWolfElement extends Components.GWolf, HTMLStencilElement {}
  var HTMLGWolfElement: {
    prototype: HTMLGWolfElement;
    new (): HTMLGWolfElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNavButtonElement extends Components.NavButton, HTMLStencilElement {}
  var HTMLNavButtonElement: {
    prototype: HTMLNavButtonElement;
    new (): HTMLNavButtonElement;
  };
  interface HTMLElementTagNameMap {
    'g-app': HTMLGAppElement;
    'g-egg': HTMLGEggElement;
    'g-wolf': HTMLGWolfElement;
    'my-component': HTMLMyComponentElement;
    'nav-button': HTMLNavButtonElement;
  }
}

declare namespace LocalJSX {
  interface GApp extends JSXBase.HTMLAttributes<HTMLGAppElement> {
    'onGameOver'?: (event: CustomEvent<void>) => void;
    'onGamePaused'?: (event: CustomEvent<boolean>) => void;
  }
  interface GEgg extends JSXBase.HTMLAttributes<HTMLGEggElement> {
    'nest'?: number;
    'onEggIsCathced'?: (event: CustomEvent<any>) => void;
    'wolfPosition'?: 'left-top' | 'left-bottom' | 'right-top' | 'right-bottom';
  }
  interface GWolf extends JSXBase.HTMLAttributes<HTMLGWolfElement> {
    'onWolfDirectionChange'?: (event: CustomEvent<WolfPosition>) => void;
    'position'?: WolfPosition;
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NavButton extends JSXBase.HTMLAttributes<HTMLNavButtonElement> {
    'direction'?: 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom';
    'onGChooseDirection'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'g-app': GApp;
    'g-egg': GEgg;
    'g-wolf': GWolf;
    'my-component': MyComponent;
    'nav-button': NavButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


