/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface GWolf {
    'position': 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom';
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface NavButton {
    'direction': 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom';
  }
}

declare global {


  interface HTMLGWolfElement extends Components.GWolf, HTMLStencilElement {}
  var HTMLGWolfElement: {
    prototype: HTMLGWolfElement;
    new (): HTMLGWolfElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLNavButtonElement extends Components.NavButton, HTMLStencilElement {}
  var HTMLNavButtonElement: {
    prototype: HTMLNavButtonElement;
    new (): HTMLNavButtonElement;
  };
  interface HTMLElementTagNameMap {
    'g-wolf': HTMLGWolfElement;
    'my-component': HTMLMyComponentElement;
    'nav-button': HTMLNavButtonElement;
  }
}

declare namespace LocalJSX {
  interface GWolf extends JSXBase.HTMLAttributes<HTMLGWolfElement> {
    'position'?: 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom';
  }
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface NavButton extends JSXBase.HTMLAttributes<HTMLNavButtonElement> {
    'direction'?: 'left-top' | 'right-top' | 'left-bottom' | 'right-bottom';
    'onGChooseDirection'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'g-wolf': GWolf;
    'my-component': MyComponent;
    'nav-button': NavButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


